name: tksbp
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  extra_pedantic: ^4.0.0
  auto_route: ^8.1.3
  auto_route_generator: ^8.0.0
  get_it: ^7.7.0
  injectable: ^2.4.2
  freezed: ^2.5.2
  freezed_annotation: ^2.4.0
  riverpod: ^2.5.1
  flutter_riverpod: ^2.5.1
  shared_preferences: ^2.2.3
  logger: ^2.3.0
  dio: ^5.4.3+1
  flutter_secure_storage: ^9.2.2
  json_annotation: ^4.9.0
  csv: ^6.0.0
  excel: ^4.0.3
  path_provider: ^2.1.3
  uuid: ^4.4.0
  permission_handler: ^11.3.1
  font_awesome_flutter: ^10.7.0
  topg:
    path: ../../../../features/topg
  i18n:
    path: ../../../../features/i18n

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  build_runner: ^2.4.9
  injectable_generator: ^2.6.1
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/
